----
#This is the pre-implementation step.
#!/usr/tools/pyenv/shims/ansible-playbook
---
#Ansible script for IOS upload
#Split into 2 to get around the closure of sockets after long upload durations
- name : IOSUPLOAD - Check file validity then upload
  hosts: "all"
  serial: 4
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_user: "{{ u }}"
    ansible_ssh_pass: "{{ p }}"

  roles:
    - iosUpload

- name : md5Check - Verify file integrity
  hosts: "all"
  serial: 15
  gather_facts: false

  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_ssh_user: "{{ u }}"
    ansible_ssh_pass: "{{ p }}"

  roles:
    - md5Check

